<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class User extends MY_Controller
{
	/**
	 * Log a user in.
	 */
	public function login()
	{
		$this->checkAjax();

		// Get the data.
		$email = $this->input->post('user');
		$pass = $this->input->post('pass');
		$remember = $this->input->post('remember');

		// Check if the max login attempts is exceeded.
		if ($this->ion_auth->is_max_login_attempts_exceeded($email))
			echo json_encode(['error' => 'The maximum number of login attempts is exceeded.']);
		// Log the user in.
		else
			$this->showResult($this->ion_auth->login($email, $pass, $remember));
	}

	/**
	 * Log the current user out.
	 */
	public function logout()
	{
		$this->ion_auth->logout();
		redirect('/ControlPanel/ControlPanel');
	}

	public function remove()
	{
		$this->checkAjax();
		$this->showResult($this->ion_auth->delete_user($this->input->get('id')));
	}

	/**
	 * Send a password recovery e-mail.
	 */
	public function passwordRecovery()
	{
		$this->checkAjax();

		$email = $this->input->post('email');

		// Get the recovery code.
		$reset = $this->ion_auth->forgotten_password($email);
		if (!$reset)
			echo json_encode(['success' => FALSE, 'message' => 'Unknown e-mail address.']);
		else
		{
			// Get the recovery code and site title.
			$code = $reset['forgotten_password_code'];
			$this->config->load('ion_auth', TRUE);
			$url = $this->config->item('site_title', 'ion_auth');
			$recoverUrl = 'http://' . $url . '/ControlPanel/User/recoverComplete/' . $code;

			// Send the recovery mail.
			$this->load->library('email');
			$this->email->from('recovery@' . $url);
			$this->email->to($email);
			$this->email->subject('Password recovery for ' . $url);
			$this->email->set_mailtype("html");
			$this->email->message(
				'<a href="' . $recoverUrl . '">Click here to reset your password.</a><br>'
				. 'If you did not request a password reset you can ignore this message.'
				. '<br><br>'
				. '<i>This is an autogenerated mail from the Scorpiac control panel.</i>'
			);
			$this->email->send();

			echo json_encode(['success' => TRUE, 'message' => 'Your password recovery e-mail has been sent.']);
		}
	}

	/**
	 * Show the password recovery view.
	 */
	public function recoverComplete($code)
	{
		$this->load->view('ControlPanel/ResetPassword', ['code' => $code]);
	}

	/**
	 * Reset the password.
	 */
	public function passwordReset()
	{
		$this->checkAjax();
		$result = ['success' => FALSE];

		// Get the code, user and new password.
		$code = $this->input->post('code');
		$user = $this->ion_auth->forgotten_password_check($code);
		$pass = $this->input->post('pass');

		// Check if the code is valid.
		if (!$user)
			$result['message'] = 'Invalid recovery code, please try resetting your password again.';
		else
		{
			// Check if the password is valid.
			$passValid = $this->passwordValid($pass);
			if ($passValid !== TRUE)
				$result['message'] = $passValid;
			else
			{
				$change = $this->ion_auth->reset_password($user->email, $pass);

				// Check if the reset was successful.
				if ($change)
					$result = ['success' => TRUE, 'message' => 'Your password has been reset.'];
				else
					$result['message'] = 'Your password could not be reset, please try resetting it again.';
			}
		}

		echo json_encode($result);
	}

	/**
	 * Register a new user.
	 */
	public function register()
	{
		$this->checkAjax();
		$this->checkLoggedInAjax();

		// Check if the user is logged in and has the right permissions.
		if (!$this->ion_auth->is_admin())
			echo json_encode(['error' => 'You are not authorized to add a new user.']);

		// Get the data.
		$email = $this->input->post('email');
		$pass = $this->input->post('pass');

		// Validate.
		$passValid = $this->passwordValid($pass);

		if (empty($email))
			echo json_encode(['error' => 'Not all fields are filled in.']);
		else if ($passValid !== TRUE)
			echo json_encode(['error' => $passValid]);
		// Register the user.
		else
			$this->showResult($this->ion_auth->register($email, $pass, $email));
	}

	/**
	 * Update a user's information.
	 */
	public function update()
	{
		$this->checkAjax();
		$this->checkLoggedInAjax();

		// Get the data.
		$data = [
			'email' => $this->input->post('email'),
			'first_name' => $this->input->post('first'),
			'last_name' => $this->input->post('last')
		];

		// Validate.
		if (empty($data['email']))
			echo json_encode(['error' => 'Not all fields are filled in.']);
		// Update the user.
		else
			$this->showResult($this->ion_auth->update($this->ion_auth->user()->row()->id, $data));
	}

	/**
	 * Change the current user's password.
	 */
	public function changePassword()
	{
		$this->checkAjax();
		$this->checkLoggedInAjax();
		$user = $this->ion_auth->user()->row();

		// Get the data.
		$oldPass = $this->input->post('oldPass');
		$pass = $this->input->post('pass');

		// Validate
		$passValid = $this->passwordValid($pass);
		$oldPassCorrect = $this->ion_auth->hash_password_db($user->id, $oldPass);

		if (!$oldPassCorrect)
			echo json_encode(['error' => 'Your old password is incorrect.']);
		else if ($passValid !== TRUE)
			echo json_encode(['error' => $passValid]);
		// Change the password.
		else
			$this->showResult($this->ion_auth->update($user->id, ['password' => $pass]));
	}

	/*==== Helper functions. ====*/

	 /**
	  * Check if a password is valid.
	  * Returns a string with the reason if the password is not valid, or TRUE otherwise.
	  */
	 private function passwordValid($pass)
	 {
		 if (strlen($pass) < 8)
			return "Your password should be at least 8 characters long.";

		return TRUE;
	 }

	 /**
	  * Echo (in JSON) either success, or the ion_auth errors.
	  */
	 private function showResult($success)
	 {
		 echo json_encode($success ? ['success' => TRUE] : ['error' => $this->ion_auth->errors()]);
	 }
}